title: "Ammartaggio"
description: "Blog di Marta Brentan â€” editoria, design e scrittura"
baseurl: ""
url: "https://ammartaggio.com"

markdown: kramdown
theme: minima

author: "Marta Brentan"
permalink: /blog/:title/
