title: "Marta Brentan â€“ Ammartaggio"
markdown: kramdown

# Abilita pagine dinamiche e blog
collections:
  posts:
    output: true

paginate: 9
paginate_path: "/blog/page:num"

plugins:
  - jekyll-paginate
